/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as KitsKitIdRouteImport } from './routes/kits.$kitId'

const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsKitIdRoute = KitsKitIdRouteImport.update({
  id: '/$kitId',
  path: '/$kitId',
  getParentRoute: () => KitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kits': typeof KitsRouteWithChildren
  '/kits/$kitId': typeof KitsKitIdRoute
  '/pedido/$id': typeof PedidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kits': typeof KitsRouteWithChildren
  '/kits/$kitId': typeof KitsKitIdRoute
  '/pedido/$id': typeof PedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kits': typeof KitsRouteWithChildren
  '/kits/$kitId': typeof KitsKitIdRoute
  '/pedido/$id': typeof PedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/kits' | '/kits/$kitId' | '/pedido/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/kits' | '/kits/$kitId' | '/pedido/$id'
  id: '__root__' | '/' | '/checkout' | '/kits' | '/kits/$kitId' | '/pedido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  KitsRoute: typeof KitsRouteWithChildren
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits/$kitId': {
      id: '/kits/$kitId'
      path: '/$kitId'
      fullPath: '/kits/$kitId'
      preLoaderRoute: typeof KitsKitIdRouteImport
      parentRoute: typeof KitsRoute
    }
  }
}

interface KitsRouteChildren {
  KitsKitIdRoute: typeof KitsKitIdRoute
}

const KitsRouteChildren: KitsRouteChildren = {
  KitsKitIdRoute: KitsKitIdRoute,
}

const KitsRouteWithChildren = KitsRoute._addFileChildren(KitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  KitsRoute: KitsRouteWithChildren,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
